language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "hIE4ENvTfhfCwXzMbNcC/xt9oVYm1b/u5aWYquEirOC25zFVtd7bFwebpOM/zyHo5rrfNDoeXU0BJLrTiVs+J5mYtfu1WTnR3XTzHgu+nHAP/2IqsKeZItVz9n9tULtS84O4sU9tScxC7PJQderrIxTSSnVIA2XEThDzz8HWj0E0LuY5XjFgBdpzDNeI79G08iHagZrgxUki5BBmc4JISTywO0xxw1lQSxLhhrxKNijeyT0XqD6mqG8bvffz7NRKpp28T5uuoJWh+teF6BFyHqzgKwnv2XxPMyo3WESlAuFaJPS8aYNGksrGBhSSDu8i7B5s/k4woP/uOSDArtx/dDCDM4dN2HlLphJ9Q0UrG1ighUqlOklRpsRPabhybucBQdyg2j847KJiKrL56rB4jN2KavVenlE2ribAaMzhy2pfbNPhZfO8ArxPbnlGqwYTdbQgvXnNSsq3QtYazm74tk8uuUAV2zVNr48mw1TIZpKppgoo73MvmeNagMaBFTf6+pQnhqZc6O8ejh9mLSzU2I8K//WdwCFBlK14uUoc74v0yVUsZHIMqWqNSOmcRR5ySB0JQNxkS/2VR9MZm1yY7mZB5r4YLjZKKjfc4UXgtOyCza+G05X38b2nXg6F7qWutCgz3P78DIzjkAktt3SteNuBbwXwKDaxYGrUKbF9Ook="
  api_key: # 4921
    secure: "fY8nBzfnSuATbeZ/gTQH4IU8RRdut3Jrs5xSzxQi6KEqo8pEQbM+Pu1Ao/tsX3pYEESXsdtAdb+TxuHlX89uadf/ZbToOXGqpVjgE+5fTEI0azgoXHIQ+N1X1B6jONiWQy0tfqzrextskY9VFnYr5x3CJfTvwfzicGleXE7c3OzxsDGIFFHC4l+8JYz98lXhtU23vuNFDlaQE32z2tueNHsUsyANvSe2/LkQlNDwEF5atpF8oaYEwkDEvicysYX2IDGucrfa74XWj/eAXi5tIW17MqQz2yu/oLr5M8E2EONUANHU3vtMLWIqzpWLk5uyAigC7LwWy1jfc95/cCTlkVjodzO9SFa1BgoRzZ+qLM5bL93HBG0FC3VJ6GvmydTxDDV06yHasoE96WcbU4+eW4cPLieWoKxwVkZJWHNSgbYU/IgUgT3C9ha/QjcucORgkgr1C1dlxPz83SCzB/cYxZ/4DndzeO7S6DK7vD+B7Z7E0JCZAvgj4ROAsQo5pUR91vi5KlF4iJCIqiBKcfLkbUfq4w50q5K+ZIS2Sv7kI+xmcnhxauYKnGv5pj2Q3b1SM7kWsoNGQKUEG0YtGKruEKZ/XFrTrtkIK7zz6Z7Eg6YQ+jCjLtH92JTBgN1+iIn+DykoaCuLKIhagmyw/Vf5ksrcLAz3TboTUVFCKaZBUaA="
  on:
    tags: true
    node: lts/*
